apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mt-pingpong 
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-pingpong 
        spec:
          containers:
          - name: ct-pingpong 
            image: gihyodocker/alpine:bash
            command: ["/bin/sh"]
            args:
              - "-c" 
              - |
                echo [`date`] ping!
                sleep 10
                echo [`date`] pong!
          restartPolicy: OnFailure
