apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-reader-clusterrolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: justinpark
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-reader
  apiGroup: rbac.authorization.k8s.io