apiVersion: v1
kind: Pod
metadata:
  name: simple-echo
spec:
  containers:
  - name: nginx 
    image: justinpark/nginx:latest 
    env: 
    - name: BACKEND_HOST
      value: localhost:8080
    ports:
    - containerPort: 80 
  - name: echo
    image: justinpark/echo:latest
    ports:
    - containerPort: 8080
apiVersion: v1
